version: '3.5'

services:
  app:
    build:
      context: .
      target: build
    volumes:
      - ./:/go/linebot-sample
    command: realize start
    ports:
      - 18080:8080
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample
      - MYSQL_USER=user
      - MYSQL_PASSWORD=passw0rd
    ports:
      - 13306:3306
