[server]
  port = ":8080"

[dbm]
  host     = "db"
  port     = ":3306"
  user     = "user"
  password = "passw0rd"
  dbname   = "sample"

[dbs]
  host     = "db"
  port     = ":3306"
  user     = "user"
  password = "passw0rd"
  dbname   = "sample"

[line]
  channel_secret = ""
  channel_token =  ""
